name: marvel-app-test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter test --coverage
    - name: Upload code coverage to GitHub
      if: (success() || failure()) && matrix.category != 'static'
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: coverage/lcov.info

  coverage_report:
      name: Generate coverage report
      needs: run-tests
      runs-on: ubuntu-latest
      steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Install missing software on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install lcov
      - name: Download code coverage from GitHub
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: coverage
      - name: Report code coverage
        uses: dethereum/github-actions-report-lcov@v1.0.0
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 20
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'code-coverage-report/index.html'
      - name: Report URL
        run: echo ${{ steps.html_preview.outputs.url }}
